name: Optimize Trading Algorithms

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 0 * * 1" 

jobs:
  optimize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk_index: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
          ] # Adjust based on the number of chunks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pystockfilter  # Add other dependencies if needed

      - name: Run optimizer for chunk
        env:
          CHUNKS_SIZE: 30
          CHUNKS_IDX: ${{ matrix.chunk_index }} # Current chunk index
        run: |
          python optimizer.py

      - name: Upload optimization results
        uses: actions/upload-artifact@v4
        with:
          name: result_${{ matrix.chunk_index }}
          path: result_*.json

  merge-results:
    runs-on: ubuntu-latest
    needs: optimize # This job will wait for all `optimize` jobs to complete
    env:
      BUILD_ID: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download all optimization artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
          pattern: result_*
          merge-multiple: true
      - name: Merge results
        run: |
          python merge_result.py

      - name: Upload merged results
        uses: actions/upload-artifact@v4
        with:
          name: merged_results
          path: merged_results.json

      - name: Get current date
        id: get_date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
  
      - name: Create GitHub release using gh-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.TAG_DATE }}-${{ env.BUILD_ID }}
          name: 'Optimize Trading Algorithms'
          body: |
            This release contains the merged optimization results for trading algorithms.
          files: merged_results.json
