name: Run Python Script and Send Email

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9:00 AM. Adjust as needed.

jobs:
  run-script-and-send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script and capture output
      id: run_script
      run: |
        python optimizer.py
          
    - name: Send Telegram Message
      id: send_telegram_message
      run: |
        MESSAGE=$(cat trading_signals.md)
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode="Markdown" \
          -d text="$MESSAGE"